import os
import numpy as np
from scipy.io import netcdf_file

def generate_sample_netcdf():
    output_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "tds", "data"))
    os.makedirs(output_dir, exist_ok=True)
    output_path = os.path.join(output_dir, "amphan_bob_temperature_sample.nc")

    # 1. Coordinate dimensions
    # Time: 3 steps (2020-05-17T00:00:00Z, 2020-05-18T00:00:00Z, 2020-05-19T00:00:00Z)
    time_values = np.array([0.0, 24.0, 48.0], dtype=np.float64)  # hours since 2020-05-17 00:00:00 UTC
    
    # Depth: 4 levels (0, 10, 25, 50 meters)
    depth_values = np.array([0.0, 10.0, 25.0, 50.0], dtype=np.float32)
    
    # Lat: 8.0 to 23.0 (0.25 deg grid -> 61 points)
    lat_values = np.linspace(8.0, 23.0, 61, dtype=np.float32)
    
    # Lon: 82.0 to 92.0 (0.25 deg grid -> 41 points)
    lon_values = np.linspace(82.0, 92.0, 41, dtype=np.float32)

    n_time = len(time_values)
    n_depth = len(depth_values)
    n_lat = len(lat_values)
    n_lon = len(lon_values)

    # 2. Synthetic Temperature Data (~26 - 30 deg C with warm-core Gaussian bump near 14N, 87E)
    temp_data = np.zeros((n_time, n_depth, n_lat, n_lon), dtype=np.float32)

    for t_idx in range(n_time):
        # Center of the warm core shifts northward as Amphan intensifies and tracks north
        center_lat = 14.0 + t_idx * 1.5
        center_lon = 87.0 + t_idx * 0.2

        for d_idx, depth in enumerate(depth_values):
            # Base temperature drops with depth: 30C at surface, ~25C at 50m
            base_temp = 30.0 - (depth / 50.0) * 4.5

            for i, lat in enumerate(lat_values):
                for j, lon in enumerate(lon_values):
                    dist_sq = ((lat - center_lat) / 2.5) ** 2 + ((lon - center_lon) / 2.5) ** 2
                    # Warm-core anomaly (+2.5 deg C at surface, attenuates with depth)
                    warm_anomaly = 2.5 * np.exp(-dist_sq) * (1.0 - depth / 70.0)
                    # Natural latitudinal gradient (slightly cooler north)
                    lat_gradient = -0.05 * (lat - 15.0)

                    temp_data[t_idx, d_idx, i, j] = base_temp + warm_anomaly + lat_gradient

    # 3. Create NetCDF file (version 2 / 64-bit offset)
    f = netcdf_file(output_path, 'w', version=2)

    f.createDimension('time', n_time)
    f.createDimension('depth', n_depth)
    f.createDimension('lat', n_lat)
    f.createDimension('lon', n_lon)

    # Time coordinate
    time_var = f.createVariable('time', 'd', ('time',))
    time_var[:] = time_values
    time_var.standard_name = 'time'
    time_var.long_name = 'time'
    time_var.units = 'hours since 2020-05-17 00:00:00 UTC'
    time_var.calendar = 'gregorian'
    time_var.axis = 'T'

    # Depth coordinate: MUST have positive = 'down' per CF-1.8 and CONTRACTS.md Section 1(b)
    depth_var = f.createVariable('depth', 'f', ('depth',))
    depth_var[:] = depth_values
    depth_var.standard_name = 'depth'
    depth_var.long_name = 'depth below sea surface'
    depth_var.units = 'm'
    depth_var.positive = 'down'
    depth_var.axis = 'Z'

    # Latitude coordinate
    lat_var = f.createVariable('lat', 'f', ('lat',))
    lat_var[:] = lat_values
    lat_var.standard_name = 'latitude'
    lat_var.long_name = 'Latitude'
    lat_var.units = 'degrees_north'
    lat_var.axis = 'Y'

    # Longitude coordinate
    lon_var = f.createVariable('lon', 'f', ('lon',))
    lon_var[:] = lon_values
    lon_var.standard_name = 'longitude'
    lon_var.long_name = 'Longitude'
    lon_var.units = 'degrees_east'
    lon_var.axis = 'X'

    # Temperature variable
    temp_var = f.createVariable('temperature', 'f', ('time', 'depth', 'lat', 'lon'))
    temp_var[:] = temp_data
    temp_var.standard_name = 'sea_water_temperature'
    temp_var.long_name = 'Sea Water Temperature'
    temp_var.units = 'degrees_C'
    temp_var._FillValue = np.float32(-9999.0)

    # Global attributes (CF-1.8 standard compliant)
    f.Conventions = 'CF-1.8'
    f.title = 'Synthetic Bay of Bengal Temperature Field - Super Cyclone Amphan Spike'
    f.institution = 'INCOIS / SIH-2026'
    f.source = 'Synthetic warm-core test grid for TDS WMS Cesium spike'
    f.history = 'Generated by spike_generate_sample_netcdf.py'

    f.close()
    print(f"Successfully generated NetCDF file at: {output_path}")
    print(f"File size: {os.path.getsize(output_path)} bytes")

if __name__ == "__main__":
    generate_sample_netcdf()
